name: HorseTP
main: com.zconami.HorseTP.HorseTPPlugin
depend: [Gringotts]
version: 1.0
authors: [Autonomy]
website: http://zconami.com/
commands:
  h:
    description: Use the help pages to find a command
    usage: /<command> help
    permission: h.list
    permission-message: You do not have permission to list your mounts
permissions:
  mount.list:
    description: Allows players to list their mounts
  mount.tp:
    description: Allows a player to tp their mount to their current location
    default: op